#!/bin/bash

# Log message to stderr
echo "Running git pre-push hook..." >&2

# Run the ktlint check
./gradlew ktlintCheck --daemon

# Capture the exit status of the ktlint check
ktlintCheckStatus=$?

# Check if the ktlint check failed
if [ $ktlintCheckStatus -ne 0 ]; then
    echo "Error: ktlint check failed with status $ktlintCheckStatus." >&2
    exit 1  # Exit with non-zero status to indicate failure
else
    echo "Ktlint check passed successfully." >&2
    exit 0  # Exit with zero status to indicate success
fi