name: Test and Build
on:
  push:

jobs:
  run-debug-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'gradle'

      - name: Grant execute permissions for gradlew
        run: chmod +x gradlew

      - name: Run Debug Tests
        run: ./gradlew clean testDebug

      - name: Upload Test Reports
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: '**/build/reports/tests/'

  run-ui-tests:
    name: Android Tests
    runs-on: macos-13
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Start Android Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 26
          target: default
          arch: x86_64
          profile: Nexus 4
          emulator-options: -no-window -no-boot-anim -no-audio -no-snapshot-load
          script: |
            adb wait-for-device
            adb shell input keyevent 82
            ./gradlew connectedAndroidTest --continue

      - name: Upload Android Test Reports
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: android-test-reports
          path: '**/build/reports/androidTests/'

  lint:
    name: Lint check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'gradle'

      - name: Grant execute permissions for gradlew
        run: chmod +x gradlew

      - name: Run lint check
        run: ./gradlew lint --stacktrace --info  # Detailed logging for diagnosing the error

  build_job:
    name: Building the APK
    runs-on: ubuntu-latest
    needs: [run-debug-tests, run-ui-tests, lint]
    if: ${{ success() }}
    steps:

      - name: Checkout
        uses: actions/checkout@v3.1.0

      - name: Format commit message and date
        id: format
        shell: bash
        run: |
          COMMIT_MSG=$(git log -1 --pretty=%s)
          FORMATTED_MSG=$(echo "$COMMIT_MSG" | sed -e 's/[^[:alnum:]]/-/g' | tr -s '-' | sed -e 's/^-//' -e 's/-$//')
          echo "artifact_name=apk-${FORMATTED_MSG}-$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT     

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'gradle'
      - name: Grant execute permissions for gradlew
        run: chmod +x gradlew

      - name: Restore Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Assemble Debug
        run: ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.format.outputs.artifact_name }}
          path: app/build/outputs/apk/debug/**.apk
          retention-days: 30

  notification:
    name: Notify About Results
    needs: [build_job]
    runs-on: ubuntu-latest
    steps:
      - name: Send mail
        uses: juanformoso/action-send-mail@1
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: Github Actions job result
        body: |
          Build job of ${{github.repository}} completed successfully!
          
          Download links:
          
          1. APK Artifact:
          https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}/artifacts/${{ needs.build_job.outputs.artifact_name }}
          
          2. Debug Test Report:
          https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}/artifacts/${{ needs.run-debug-tests.outputs.debug_report_name }}
          
          3. UI Test Report:
          https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}/artifacts/${{ needs.run-ui-tests.outputs.ui_report_name }}
        to: aleksandrbasanets2012@gmail.com
        from: bookTrails2024@gmail.com