name: Test and Build
on:
  push:

jobs:
  build_job:
    name: Building the APK
    runs-on: ubuntu-latest
    if: ${{ success() }}
    steps:

      - name: Checkout
        uses: actions/checkout@v3.1.0

      - name: Format commit message and date
        id: format
        shell: bash
        run: |
          COMMIT_MSG=$(git log -1 --pretty=%s)
          FORMATTED_MSG=$(echo "$COMMIT_MSG" | sed -e 's/[^[:alnum:]]/-/g' | tr -s '-' | sed -e 's/^-//' -e 's/-$//')
          echo "artifact_name=apk-${FORMATTED_MSG}-$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT     

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'gradle'
      - name: Grant execute permissions for gradlew
        run: chmod +x gradlew

      - name: Restore Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Assemble Debug
        run: ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.format.outputs.artifact_name }}
          path: app/build/outputs/apk/debug/**.apk
          retention-days: 30

  notification:
    name: Notify About Results
    needs: [build_job]
    runs-on: ubuntu-latest
    steps:
      - name: Send mail
        uses: juanformoso/action-send-mail@1
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: Github Actions job result
          content_type: text/html
          body:
            <a href='https://github.com/Alex20280/GitActionsTest/actions/runs/$GITHUB_RUN_ID/artifacts/'>Download Artifacts</a><br><br>
          to: aleksandrbasanets2012@gmail.com
          from: bookTrails2024@gmail.com